### ISSUE TITLE
React Router V5 vs V6 - diferenças nas declarações de: BrowserRouter, Switch, useHistory,  exact entre outras

### ISSUE THREAD

**Issue by huannvictor** [rocketseat-education/nlw-06-reactjs#8]
Na aula 02 encontrei um problema com a versão do `react-router-dom` e como tratar as rotas. Abri um request #7 e lá enviei a solução.
Porem, por conta dessa nova versão outras diferenças de como fazer as declarações mudaram também, então segue aqui.  

---
### `<Switch>` tornou: `<Routes>`

```js
// v5
<Switch>
  <Route exact path="/" component={Home} />
  <Route path="/profile" component={Profile} />
</Switch>


// v6
<Routes>
  <Route path="/" element={<Home />} />
  <Route path="/profile" element={<Profile />} />
</Routes>
```
Na v6, você não precisa mais usar um `exact`  

---
### `useHistory` tornou: `useNavigate`

```js
// v5
import { useHistory } from 'react-router-dom';

function MyButton() {
  let history = useHistory();
  function handleClick() {
    history.push('/home');
  };
  return <button onClick={handleClick}>Submit</button>;
};


// v6
import { useNavigate } from 'react-router-dom';

function MyButton() {
  let navigate = useNavigate();
  function handleClick() {
    navigate('/home');
  };
  return <button onClick={handleClick}>Submit</button>;
};
```
Na v6 não se faz necessário o uso do `.push` ou do `.replace`
```js
// v5
history.push('/home');
history.replace('/home');

// v6
navigate('/home');
navigate('/home', {replace: true});
```  
---

Essas foram as soluções que encontrei em dezembro/2021.
fontes: https://ichi.pro/pt/o-que-ha-de-novo-no-roteador-react-v6-54507686506060 e https://dev.to/arunavamodak/react-router-v5-vs-v6-dp0

**Comment by danilo-vieira** [comment]
Faaala @huannvictor tudo bem?
Essas mudanças do React Router DOM aconteceram após a release da V6. Essa foi uma atualização com breaking changes conforme você pontuou mas isso porque a biblioteca teve uma atualização major, ou seja, ganhou uma nova versão (v6). Isso não significa que a v5 perdeu o suporte. Ela continua sendo mantida (r provavelmente continuará por um bom tempo) já que, como mencionado, ela possui breaking changes e muitas empresas usam a v5 em produção.

O que eu proponho a você e pra mais alguém que estiver vendo essa issue, é que siga as aulas usando a v5 do React Router. Assim você terá a experiência e aprendizado da API na v5 (que continua sendo muito utilizada) e pode aprender posteriormente a v6, tratando assim as duas versões como coisas distintas 💜

**Comment by huannvictor** [comment]
ah, valeu pela explicação @danilo-vieira!
Então eu só preciso instalar a v5 e usar normalmente.

**Comment by danilo-vieira** [comment]
> ah, valeu pela explicação @danilo-vieira!
> Então eu só preciso instalar a v5 e usar normalmente.

Isso mesmo! 😉
